# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_web', '0002_auto_20191107_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imgpath', models.CharField(max_length=20)),
                ('synopsis', models.CharField(max_length=20)),
            ],
        ),
    ]
