# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_instructor'),
    ]

    operations = [
    ]
