# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-27 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0004_auto_20200204_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='optionalfund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u57fa\u91d1\u540d\u79f0')),
                ('fundcode', models.CharField(max_length=100, verbose_name='\u57fa\u91d1\u4ee3\u7801')),
                ('hold', models.CharField(max_length=100, verbose_name='\u5f53\u524d\u6301\u6709')),
                ('progressiveincome', models.CharField(max_length=100, verbose_name='\u7d2f\u8ba1\u6536\u76ca')),
                ('rateofreturn', models.CharField(max_length=100, verbose_name='\u7d2f\u8ba1\u6536\u76ca\u7387')),
            ],
            options={
                'db_table': 'optionalfund',
            },
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
