# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0005_auto_20200527_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradingrules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingindex', models.CharField(max_length=100, verbose_name='\u8ddf\u8e2a\u6307\u6570')),
                ('start', models.CharField(max_length=100, verbose_name='\u5f00\u59cb\u4e70\u5165\u70b9\u6570')),
                ('startingamount', models.CharField(max_length=100, verbose_name='\u5f00\u59cb\u4e70\u5165\u91d1\u989d')),
                ('secondamount', models.CharField(max_length=100, verbose_name='\u7b2c\u4e8c\u4e2a\u6863\u4f4d\u4e70\u5165\u91d1\u989d')),
                ('sellpoint', models.CharField(max_length=100, verbose_name='\u5356\u51fa\u70b9\u4f4d')),
                ('sellshare', models.CharField(max_length=100, verbose_name='\u5356\u51fa\u4efd\u989d\u767e\u5206\u6bd4')),
            ],
            options={
                'db_table': 'tradingrules',
            },
        ),
    ]
