# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-03 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0006_tradingrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingrules',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='\u57fa\u91d1\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingrules',
            name='secondamount',
            field=models.CharField(max_length=100, verbose_name='\u7b2c\u4e8c\u4e2a\u6863\u4f4d\u4e70\u5165\u70b9\u4f4d'),
        ),
    ]
