# Generated by Django 3.0.6 on 2020-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0007_auto_20200703_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='股票名称')),
                ('code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('newest', models.CharField(max_length=20, verbose_name='最新价')),
                ('quote_change', models.CharField(max_length=10, verbose_name='涨跌幅')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
